services:
  app:
    build: .
    container_name: video-artifact-engine
    env_file:
      - .env
    volumes:
      - .:/app
      - /tmp/video_processing:/tmp/video_processing
    ports:
      - "8000:8000"
    command: ["uv", "run", "python", "src/main.py"]